---
- hosts: localhost
  vars:
    # https://github.com/ycm-core/YouCompleteMe/wiki/Building-Vim-from-source
    vim_version: v8.2.0439
    deps:
      - libtool-bin
      - libncurses5-dev
      - libgtk-3-dev
      - libatk1.0-dev
      - libcairo2-dev
      - libx11-dev
      - libxpm-dev
      - libxt-dev
      - python-dev
      - python3-dev
      - ruby-dev
      - libperl-dev
      - git

  tasks:

    - name: Install deps
      package:
        name: "{{ item }}"
        state: present
      become: yes
      loop: "{{ deps }}"

    - name: Vim source code
      block:
        - name: clone
          git:
            repo: "https://github.com/vim/vim.git"
            force: yes
            dest: ~/src/vim
            version: "{{ vim_version }}"

      rescue:
        - name: git reset
          command: git reset --hard HEAD
          args:
            chdir: ~/src/vim

        - name: git master
          command: git checkout master
          args:
            chdir: ~/src/vim

        - name: git pull
          command: git pull
          args:
            chdir: ~/src/vim

        - name: git checkout
          command: "git checkout {{ vim_version }}"
          args:
            chdir: ~/src/vim

    - name: Make clean
      make:
        chdir: ~/src/vim
        target: distclean
        params:
          NUM_THREADS: 2

    - name: configure
      shell: |
        ./configure \
          --enable-rubyinterp=yes \
          --enable-python3interp=yes \
          --with-python3-config-dir=$(python3-config --configdir) \
          --enable-perlinterp=yes \
          --enable-gui=gtk3 \
          --enable-cscope \
          --prefix=$HOME
      args:
        chdir: ~/src/vim

    - name: Make vim
      make:
        chdir: ~/src/vim
        params:
          NUM_THREADS: 2

    - name: Make test vim
      make:
        chdir: ~/src/vim
        target: test
        params:
          NUM_THREADS: 2

    - name: Make install vim
      make:
        chdir: ~/src/vim
        target: install
