#!/bin/sh

#
# SYNOPSIS
# 
# Redunce or increase brightness by a given percent.

CHANGE=$1

# base dir for backlight class
basedir="/sys/class/backlight/intel_backlight"

# get current brightness
old_brightness=$(cat $basedir"/brightness")

# get max brightness
max_brightness=$(cat $basedir"/max_brightness")

# get current brightness %
old_brightness_p=$(( 100 * $old_brightness / $max_brightness ))

# calculate new brightness % 
new_brightness_p=$(( $old_brightness_p $CHANGE ))

# calculate new brightness value
new_brightness=$(( $max_brightness * $new_brightness_p / 100 ))

if [ $new_brightness -gt $max_brightness ]
then
   echo Too bright, max == $max_brightness
elif [ $new_brightness -lt 0 ]
then
   echo Too dim, current is $old_brightness_p
else
# set the new brightness value
   echo "$new_brightness" > "${basedir}/brightness"
fi
