#!/bin/bash

dir=${1:-~/wallpaper}
delay=${2:-180}

# Get screen size
screen_size=$(xdpyinfo | awk '/dimensions:/ { print $2 }')

cd $dir || exit

while true; do
   image=$(ls *.jp?g *.png | shuf -n 1)
   ext=${image##*.}

   convert $image -resize "${screen_size}>" /tmp/wallpaper.${ext}
   feh --bg-center --no-fehbg /tmp/wallpaper.${ext}
   sleep $delay
done

