#!/bin/bash

dir=${1:-~/wallpaper}
delay=${2:-180}

# Get screen size
screen_size=$(xdpyinfo | awk '/dimensions:/ { print $2 }')

cd $dir || exit

while true; do
   image=$(ls *.jp?g *.png | shuf -n 1)
   ext=${image##*.}

   convert $image -resize "${screen_size}>" /tmp/$image
   feh --bg-center --no-fehbg $dir/$image
   echo $image > /tmp/wallpaper
   sleep $delay
done

