=pod

=head1 Perl cheatsheet

Can't remember how to do that thing in Perl? Neither can I, so I write it down.
I hope you find this helpful.

=head2 Named parameters to subroutines.

=over 3

   sub named_params_example
   {
      my %args = @_;
      # Use my ( $self, %args ) = @_; if you are in object land.

      say $args{one};
      say $args{two};
   }

   named_params_example(
      one => "First argument",
      two => "Second argument"
   );

=head3 With default values

=over 3

   sub named_params_with_defaults
   {
      my %args = (
         one => 'default value',
         two => 'default value',
         @_, # Will override the above values.
      );
   }

   named_params_with_defaults(
      one => "override arg 'one'"
   );

=back

=head2 Return named params from a subroutine
   
=over 3

   sub foo
   {
      my $clause = 'This is a clause';
      my @param = qw/ pone ptwo pthee /;

      return (
         clause => $clause,
         params => \@param
      );
   }

   my %r = foo();

   say "clause = [$r{clause}]";
   for my $p ( @{ $r{params} } )
   {
      say "param = [$p]";
   }

=back

=head3 Or as a reference

=over 3

sub foo
{
   return {
      one => 1,
      two => 2,
   }
}

my $hashref = foo();
say "foo{one} = [$hashref->{one}]";

=back

=head2 Shell search and replace

=over 3

   find /path -name "*.*" -exec perl -pi -e 's///g' {} \;

=back

=head2 Search and replace, keep original and assign change to new variable.

=over 3

   ( my $new_var = $original ) =~ s/teh/the/g ;

=back

=head2 Match and store match in a single line

=over 3 

   ( my $match ) = $original =~ m/(kept)/;

=back

=head2 What module should I use?

Consult CPAN's Task::Kensho.

=head2 Licence

The MIT License (MIT)

Copyright (c) 2014 Neil H Watson

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

=cut
